<?php
use ZendService\Flickr\Flickr;

$config = $this->layout()->configFlickr;
// $flickr = new Flickr($config['key']);
// $flickr->getHttpClient()->setOptions(array('sslverifypeer' => false));
?>
<section id="ef-header">

      <a href="/" id="ef-logo"><img src="/assets/logo.png" alt="Puebla Pictures"></a>

      <nav class="top-bar">
        <ul class="title-area">
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Nav Section -->
          <ul>
            <li class="has-dropdown active"><a href="/">Home</a>
              
            </li>
            
           
            <li class="has-dropdown"><a href="#">Grupos</a>
                <ul class="dropdown">
                <?php foreach ($config['groups'] as $group):?>
                    <li><a href="/grupos/<?php echo $group['uri']?>"><?php echo $group['title']?></a></li>
                <?php endforeach;?>
                </ul>
            </li>
            
            <li class="has-dropdown"><a href="portfolio-gutters-fw-page-1.html">Otras Galerías</a>

              <ul class="dropdown">
                <li class="has-dropdown"><a href="http://www.turista.com.mx">Turista</a>
                  <ul class="dropdown">
                    <li><a href="http://www.chiapaspictures.com">Chiapas</a></li>
                    <li><a href="http://www.mexicopictures.net">Mexico</a></li>
                    <li><a href="http://www.cancunpictures.net">Cancún</a></li>
                    <li><a href="http://turistacancun.com/gallery">Cancún Image Gallery</a></li>
                    <li><a href="http://www.yucatanpictures.com">Yucatán</a></li>
                  </ul>

                </li>
                <li class="has-dropdown"><a href="#">Social</a>

                  <ul class="dropdown">
                    <li><a href="https://www.flickr.com/photos/turistamexico/">Flickr</a></li>
                  </ul>

                </li>
              </ul>

            </li>
            
          </ul>

        </section>
      </nav>
    </section>
    
    <div id="ef-slider-overlay"><img src="/assets/slider-overlay.png" alt=""></div>
    
    
