<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Galerias\Module'                        => __DIR__ . '/Module.php',
    'Galerias\Controller\IndexController' => __DIR__ . '/src/Galerias/Controller/IndexController.php',
    'GaleriasTest\Framework\TestCase'        => __DIR__ . '/tests/Galerias/Framework/TestCase.php',
    'GaleriasTest\SampleTest'                => __DIR__ . '/tests/Galerias/SampleTest.php',
);
