<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foto\Module'                        => __DIR__ . '/Module.php',
    'Foto\Controller\IndexController' => __DIR__ . '/src/Foto/Controller/IndexController.php',
    'FotoTest\Framework\TestCase'        => __DIR__ . '/tests/Foto/Framework/TestCase.php',
    'FotoTest\SampleTest'                => __DIR__ . '/tests/Foto/SampleTest.php',
);
