<?php 
//Zend\Debug\Debug::dump($this->photos[0]);
 $this->headtitle($this->photos[0]['info']['title'] . ' (' . $this->photos[0]['id'] .')');
 if ($this->photos[0]['info']['description'] == '') {
     $descripcion = 'Detalles de la Fotografía ' . $this->photos[0]['info']['title'];
 } else {
     $descripcion = $this->photos[0]['info']['description'];
 }
 $this->headmeta()->appendName('description', substr(strip_tags($descripcion),0,150));
 $tags = preg_split('/\s+/', $this->photos[0]['info']['tags']);
 $keywords = 'foto';
 foreach ($tags as $tag) {
     if ($tag <> '') {
         $keywords = $keywords . ', ' . $tag;
     }
 }
 $this->headmeta()->appendName('keywords', $keywords);
?>
<section id="ef-page" class="ef-has-sidebar">

      <div class="ef-featured-img">
        <div class="ef-slider-holder">

          <div class="ef-post-carousel clearfix">
            <ul class="slides">
              <?php foreach ($this->photos as $photo):?>
                <li class="ef-slide"><img src="<?php echo $photo['details']['Medium 800']->uri?>" alt=""></li>
              <?php endforeach;?>
<!--               <li class="ef-slide"><img src="assets/content/img_768x512.jpg" alt=""></li> -->
<!--               <li class="ef-slide"><img src="assets/content/img_768x512-1.jpg" alt=""></li> -->
            </ul>
          </div>

          <span class="ef-preloader"><i class="icn-spin6 animate-spin"></i></span>

          <div class="ef-post-slider-ctrls ef-round">
            <a href="#" class="post-slider-prev icn-angle-left"></a>
            <span class="ef-post-slider-counter"></span>
            <a href="#" class="post-slider-next icn-angle-right"></a>
          </div>

        </div>
      </div>

      <div class="row">

        <div class="col-md-4 col-md-push-8">
          <div id="ef-exif" class="ef-page-sidebar">
            <h6>Exif info</h6>

            <div id="ef-exif-slider" class="clearfix">

              <ul class="slides">
                <?php foreach ($this->photos as $photo):?>
                <li class="ef-slide">
                  <ul>
                    <?php $i=0?>
                    <?php foreach ($photo['exif'] as $key=>$value):?>
                    <li><strong><?php echo $key?>:</strong> <?php echo $value?></li>
                    <?php
                       $i++;
                       if ($i > 6) {
                           break;
                       } 
                    ?>
                    <?php endforeach;?>
                  </ul>
                </li>
                <?php endforeach;?>
              </ul>
            </div>
          </div>

        </div>

        <div class="col-md-8 col-md-pull-4">
          <div class="ef-page-inner">

            <small class="ef-post-info">Category: <a href="#">Fashion</a></small>

            <h3><?php echo $this->photos[0]['info']['title']?></h3>

            <p><?php echo $this->photos[0]['info']['description']?></p>
            
            <?php if ($this->photos[0]['info']['tags'] <> ''):?>
            
            <?php // \Zend\Debug\Debug::dump($matches)?>
            <div class="tagcloud ef-posted-in">
              <ul class="wp-tag-cloud">
                <li class="ef-taghead">Etiquetado:</li>
                <?php foreach ($tags as $tag):?>
                    <?php if ($tag <> ''):?>
                        <li><a rel="tag" href="#"><?php echo $tag?></a></li>
                    <?php endif;?>
                <?php endforeach;?>
              </ul>
            </div>
            <?php endif;?>
            <button type="button" class="btn ef-hollow-btn btn-primary btn-xs">
            <a href="<?php echo $this->photos[0]['info']['urls']?>">Abrir en Flickr</a>
            </button>  
          </div>
        </div>
      </div>

    </section>

