<?php 
// Zend\Debug\Debug::dump($this->photoDetails);die();
?>
<section id="ef-page" class="ef-has-sidebar">

      <div class="ef-featured-img">
        <div class="ef-slider-holder">

          <div class="ef-post-carousel clearfix">
            <ul class="slides">
              <li class="ef-slide"><img src="<?php echo $this->photoDetails['Medium 800']->uri?>" alt=""></li>
<!--               <li class="ef-slide"><img src="assets/content/img_768x512.jpg" alt=""></li> -->
<!--               <li class="ef-slide"><img src="assets/content/img_768x512-1.jpg" alt=""></li> -->
            </ul>
          </div>

          <span class="ef-preloader"><i class="icn-spin6 animate-spin"></i></span>

          <div class="ef-post-slider-ctrls ef-round">
            <a href="#" class="post-slider-prev icn-angle-left"></a>
            <span class="ef-post-slider-counter"></span>
            <a href="#" class="post-slider-next icn-angle-right"></a>
          </div>

        </div>
      </div>

      <div class="row">

        <div class="col-md-4 col-md-push-8">
          <div id="ef-exif" class="ef-page-sidebar">
            <h6>Exif info</h6>

            <div id="ef-exif-slider" class="clearfix">

              <ul class="slides">
                <li class="ef-slide">
                  <ul>
                    <?php $i=0?>
                    <?php foreach ($this->photoExif as $key=>$value):?>
                    <li><strong><?php echo $key?>:</strong> <?php echo $value?></li>
                    <?php
                       $i++;
                       if ($i > 6) {
                           break;
                       } 
                    ?>
                    <?php endforeach;?>
                  </ul>
                </li>

                <li class="ef-slide">
                  <ul>
                    <li><strong>Camera:</strong> Nikon D7100</li>
                    <li><strong>Software:</strong> Adobe Lightroom CS4 Mac OS</li>
                    <li><strong>DateTime:</strong> 2013:07:21 02:05:25</li>
                    <li><strong>Longitude:</strong> 2,11,15.781005859375, <strong>latitude:</strong> 53,0,49.283935546875</li>
                  </ul>                  
                </li>

                <li class="ef-slide">
                  <ul>
                    <li><strong>Camera:</strong> Canon EOS 5D Mark III</li>
                    <li><strong>Software:</strong> Adobe Photoshop CS5 Mac OS</li>
                    <li><strong>DateTime:</strong> 2013:03:08 11:27:49</li>
                    <li><strong>Longitude:</strong> 2,11,15.781005859375, <strong>latitude:</strong> 53,0,49.283935546875</li>
                  </ul>                  
                </li>
              </ul>
            </div>
          </div>

        </div>

        <div class="col-md-8 col-md-pull-4">
          <div class="ef-page-inner">

            <small class="ef-post-info">Category: <a href="#">Fashion</a></small>

            <h3><?php echo $this->photoInfo['title']?></h3>

            <p><?php echo $this->photoInfo['description']?></p>
            
            <?php if ($this->photoInfo['tags'] <> ''):?>
            <?php 
            $tags = preg_split('/\s+/', $this->photoInfo['tags']);
            ?>
            <?php // \Zend\Debug\Debug::dump($matches)?>
            <div class="tagcloud ef-posted-in">
              <ul class="wp-tag-cloud">
                <li class="ef-taghead">Etiquetado:</li>
                <?php foreach ($tags as $tag):?>
                    <?php if ($tag <> ''):?>
                        <li><a rel="tag" href="#"><?php echo $tag?></a></li>
                    <?php endif;?>
                <?php endforeach;?>
              </ul>
            </div>
            <?php endif;?>
            <button type="button" class="btn ef-hollow-btn btn-primary btn-xs">
            <a href="<?php echo $this->photoDetails['Medium 800']->clickUri?>">Abrir en Flickr</a>
            </button>  
          </div>
        </div>
      </div>

    </section>

