<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AdeFlickrGallery\Module'                        => __DIR__ . '/Module.php',
    'AdeFlickrGallery\Controller\IndexController' => __DIR__ . '/src/AdeFlickrGallery/Controller/IndexController.php',
    'AdeFlickrGalleryTest\Framework\TestCase'        => __DIR__ . '/tests/AdeFlickrGallery/Framework/TestCase.php',
    'AdeFlickrGalleryTest\SampleTest'                => __DIR__ . '/tests/AdeFlickrGallery/SampleTest.php',
);
