 <section id="ef-page-header">
      <div id="ef-head-inner">
        <div id="ef-page-title">

          <span><?php echo $this->pageTitle?></span>

          <div id="ef-select-wrapper">
            <ul id="ef-filter" class="option-set list-inline" data-option-key="filter">
              <li class="ef-currentClass ef-all-works"><a data-filter="*" href="#" class="icn-ef">All</a></li>
              <li><a data-filter=".category-1" href="#" class="icn-ef">Nature</a></li>
              <li><a data-filter=".category-2" href="#" class="icn-ef">Architecture</a></li>
              <li><a data-filter=".category-3" href="#" class="icn-ef">People</a></li>
              <li><a data-filter=".category-4" href="#" class="icn-ef">Fashion</a></li>
              <li><a data-filter=".category-5" href="#" class="icn-ef">Lifestyle</a></li>
              <li><a data-filter=".category-6" href="#" class="icn-ef">Technical</a></li>
              <li><a data-filter=".category-7" href="#" class="icn-ef">Miscellanous</a></li>
            </ul>
          </div>

        </div>
        <div id="ef-page-controls">
          <a id="ef-widgets-tab" class="icn-ef" href="#"></a>
        </div>
      </div>
      <aside id="ef-widgets">
        <div id="ef-widgets-pane">
          <div id="ef-widgets-inner">

            <section class="ef-widget">
              <div class="widget_text widget">
                <h6><?php echo $this->groupInfo['name']?></h6>
              
                <p><?php echo ($this->groupInfo['description'])?></p>
              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_tag_cloud">
                <h6>Portfolio tags</h6>
              
                <div class="tagcloud">
                  <ul class="wp-tag-cloud">
                    <li><a class="tag-link" title="1 topic" href="#">man</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">street</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">wall</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">sky</a></li>
                    <li><a class="tag-link" title="3 topics" href="#">development</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">fashion</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">love</a></li>
                    <li><a class="tag-link" title="4 topics" href="#">dark</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">bridge</a></li>
                    <li><a class="tag-link" title="3 topics" href="#">cooking</a></li>
                    <li><a class="tag-link" title="4 topics" href="#">light</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">night</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">night</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">website</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">road</a></li>
                    <li><a class="tag-link" title="5 topics" href="#">party</a></li>
                  </ul>
                </div>

              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_flickr">
                <h6>Flickr feed</h6>
              
<!--                 <ul class="jflickr clearfix"></ul> -->

              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_indtagram">
                <h6>From Instagram</h6>
              
<!--                 <ul class="instagram clearfix"></ul> -->

              </div>
            </section>

          </div>
        </div>
      </aside>
    </section>