 <div id="ef-slider-overlay"><img src="/assets/slider-overlay.png" alt=""></div>
 <section id="ef-page-header">
      <div id="ef-head-inner">
        <div id="ef-page-title">

          <span><?php echo $this->pageTitle?></span>

          <div id="ef-select-wrapper">
            <ul id="ef-filter" class="option-set list-inline" data-option-key="filter">
              <li class="ef-currentClass ef-all-works"><a data-filter="*" href="#" class="icn-ef">All</a></li>
              <?php foreach ($this->categorias as $categoria):?>
                 <li><a data-filter=".category-<?php echo $categoria?>" href="#" class="icn-ef"><?php echo $categoria?></a></li>
              <?php endforeach;?>
              
             
            </ul>
          </div>

        </div>
        <div id="ef-page-controls">
          <a id="ef-widgets-tab" class="icn-ef" href="#"></a>
        </div>
      </div>
      <aside id="ef-widgets">
        <div id="ef-widgets-pane">
          <div id="ef-widgets-inner">

            <section class="ef-widget">
              <div class="widget_text widget">
                <h6><?php echo $this->albumInfo['title']?></h6>
                <?php if (isset($this->albumInfo['description'])):?>
                <p><?php echo ($this->albumInfo['description'])?></p>
                <?php endif;?>
              </div>
            </section>
            
            <section class="ef-widget">
              <div class="widget_text widget">
                <h6>Discusiones</h6>
                <div class="tagcloud">
                <ul class="wp-tag-cloud">
                <?php //foreach ($this->groupTopics as $topicId => $topic):?>
                <li>
                <a class="btn ef-hollow-btn btn-default"
                href="https://www.flickr.com/groups/<?php echo $this->id?>/discuss/<?php //echo $topicId?>/">
                <?php //echo $topic?></a></li>
                <?php //endforeach;?>
                </ul>
                </div>
              </div>
            </section>
            
            <section class="ef-widget">
              <div class="widget_text widget">
                <?php $pages = ceil($this->albumInfo['count_photos'] / 20)?>
                <h6> <?php echo $this->albumInfo['count_photos']?> Fotos en 
                <?php echo $pages?> Páginas</h6>
                <div class="tagcloud">
                  <ul class="wp-tag-cloud">
                      
                      <?php for ($i=1; $i<=$pages; $i++):?>
                         
                         <li><a 
                         class="btn ef-hollow-btn btn-<?php if ($i == $this->page) echo 'primary'; else echo 'default'?>" 
                         title="Página <?php echo $i?>" 
                         href="/album/<?php echo $this->id?>/pag/<?php echo $i?>"><?php 
                         echo $i?></a></li>
                         <?php if ( ($i > 20) && ($i+9 < $pages)) $i = $i + 9?>
                      <?php endfor;?>
                  </ul>
                </div>
              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_tag_cloud">
                <h6>Etiquetas</h6>
                <div class="tagcloud">
                  <ul class="wp-tag-cloud">
                      <?php foreach ($this->tags as $tag=>$count):?>
                        <?php if ($tag <> ''):?>
                         <li><a class="tag-link" title="1 topic" href="/tag/<?php echo $tag?>"><?php echo $tag?></a></li>
                        <?php endif;?>
                      <?php endforeach;?>
                  </ul>
                </div>
              </div>
            </section>


          </div>
        </div>
      </aside>
    </section>