<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Grupos\Module'                        => __DIR__ . '/Module.php',
    'Grupos\Controller\IndexController' => __DIR__ . '/src/Grupos/Controller/IndexController.php',
    'GruposTest\Framework\TestCase'        => __DIR__ . '/tests/Grupos/Framework/TestCase.php',
    'GruposTest\SampleTest'                => __DIR__ . '/tests/Grupos/SampleTest.php',
);
